name: simple-workflow

on: 
    workflow_dispatch:

jobs:
    run-hello-world:
      runs-on: ubuntu-latest
      steps:
          - name: Run hello world
            run: 
              python code/hello_world.py
